# Use official lightweight Python image
FROM python:3.11-slim

# Set work directory inside the container
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

# Copy the app code
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the Flask default port
EXPOSE 5000

# Define the command to run the app
CMD ["python", "app_1.py"]
